before_install:
    - openssl aes-256-cbc -K $encrypted_9cc587287f32_key -iv $encrypted_9cc587287f32_iv -in snappy-m-o-private.key.enc -out snappy-m-o-private.key -d

env:
    global:
        - secure: "jnEHappJziaTbwGwQ5mVJxiSyFVPEyIRgnydbe5ia0pA6z+puk35ltnH8DDGRruH/nxe+ONZIvtw4iw7GGlRcHFXjHV8Atz9bZvXnC1VhOpzEZx/vGTOEKlLvT4cyYiA4D+bGfO3aVHJAzF+x3wgtZsC3DoVNtYEqTN01OPDKydZ1vMcb3mzGUS6V0OpnVZvrFSegVS3ocKowgDqvS97mSCEO4MUdVm4WadY0Eez497j3Ght5hSUnPZBulaw1BbhJ1b1lYHDYMaBgnCMQu89pGzHcjuU3/Te9h3dJgptDVZkojgvpWCUzdtKY6kS5Ha9krI5MdPubAxrsGHFX8V5z+xiGTAJnEAIu4gyzE9S8epeycCjYIZUWgMCtMwxBXDFi6YW4Mg07hWX0GU8E8WAe4zPEmnl/KePULtEkw/8JBUgVJxdHtMda9yQBOeG0tWGsqupeUm9HavFxBcxgA8524IgzuO68w1hXM6j3ILViLBKTP2a0hM5qUy8mnIw9DBnQ7IE521c8A9JR7xAIwSr42zC9wxXxWgdSjPa/CjruGh/R0SYb2s8kFs/rvFCEIiSuMSVxvR6IUL+cByqZRFsPidDNA0Ol+1L+QPh5lTaKSUzVegiEwRLFmGsz/Rd4j15JdplvatTQjDOXBWxJ8hU/+eJG/mKx6AKznHwj2kaNnM="

services:
    - docker

script:
    - docker run --rm -e "BUILD_PASSWORD=$BUILD_PASSWORD" -e "BUILD_KEY=$(cat snappy-m-o-private.key)" -e "TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER" -u travis ubuntucore/snapd-daily-build
